CREATE SCHEMA IF NOT EXISTS __CATALOG__.bronze;

CREATE OR REPLACE TABLE __CATALOG__.bronze.state_alias_reference AS
SELECT * FROM VALUES
  ('andaman and nicobar islands', 'Andaman And Nicobar Islands'),
  ('andaman & nicobar islands', 'Andaman And Nicobar Islands'),
  ('andhra pradesh', 'Andhra Pradesh'),
  ('arunachal pradesh', 'Arunachal Pradesh'),
  ('assam', 'Assam'),
  ('bihar', 'Bihar'),
  ('chandigarh', 'Chandigarh'),
  ('chhattisgarh', 'Chhattisgarh'),
  ('dadra and nagar haveli and daman and diu', 'Dadra And Nagar Haveli And Daman And Diu'),
  ('dadra & nagar haveli and daman & diu', 'Dadra And Nagar Haveli And Daman And Diu'),
  ('delhi', 'Delhi'),
  ('nct of delhi', 'Delhi'),
  ('national capital territory of delhi', 'Delhi'),
  ('goa', 'Goa'),
  ('gujarat', 'Gujarat'),
  ('haryana', 'Haryana'),
  ('himachal pradesh', 'Himachal Pradesh'),
  ('jammu and kashmir', 'Jammu And Kashmir'),
  ('j&k', 'Jammu And Kashmir'),
  ('jharkhand', 'Jharkhand'),
  ('karnataka', 'Karnataka'),
  ('kerala', 'Kerala'),
  ('ladakh', 'Ladakh'),
  ('lakshadweep', 'Lakshadweep'),
  ('madhya pradesh', 'Madhya Pradesh'),
  ('maharashtra', 'Maharashtra'),
  ('manipur', 'Manipur'),
  ('meghalaya', 'Meghalaya'),
  ('mizoram', 'Mizoram'),
  ('nagaland', 'Nagaland'),
  ('odisha', 'Odisha'),
  ('orissa', 'Odisha'),
  ('puducherry', 'Puducherry'),
  ('pondicherry', 'Puducherry'),
  ('punjab', 'Punjab'),
  ('rajasthan', 'Rajasthan'),
  ('sikkim', 'Sikkim'),
  ('tamil nadu', 'Tamil Nadu'),
  ('telangana', 'Telangana'),
  ('tripura', 'Tripura'),
  ('uttar pradesh', 'Uttar Pradesh'),
  ('uttarakhand', 'Uttarakhand'),
  ('uttaranchal', 'Uttarakhand'),
  ('west bengal', 'West Bengal')
AS t(alias, canonical_state);
